# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "nfra/kickstart-flavor-php:unstable"

packages: ["php8.0-sqlite3"]

command:
  build:
    - "composer update"
  init:
  test:
    - "ptest"
  run:
  dev:
    - "echo 'I am executed in dev mode'"
