<?php


namespace Phore\UniDb\Driver\Sqlite;


use Phore\UniDb\Driver;
use Phore\UniDb\Schema\Schema;
use Phore\UniDb\Schema\TableSchema;
use Phore\UniDb\Stmt\Stmt;

class SqliteDriver extends Driver\PDO\PdoDriver
{


    public function createSchema() :string
    {

        $stmts = "\n# Autogenerated schema\n";
        foreach ($this->schema->getTableNames() as $tableName) {
            $schema = $this->schema->getSchema($tableName);

            $stmt = "CREATE TABLE IF NOT EXISTS $tableName (\n";
            $defs = [$schema->getPkCol() . " VARCHAR PRIMARY KEY ASC"];
            foreach ($schema->getIndexes() as $index) {
                $defs[] = $index . " VARCHAR UNIQUE";
            }
            $defs[] = $schema->getDataCol() . " TEXT";

            $stmt .= implode(", ", $defs);
            $stmt .= ");\n";
            $stmts .= $stmt;
        }

        $this->PDO->exec($stmt);
        return $stmts;
    }
}